### PR TITLE
added capability to import multiple field links

### PR DESCRIPTION
**Pull request by gryphonmyers**
Cockpit supports multiple entries in the collection link field. This commit will split the given column (for now, split delimiter is the pipe character) and do a lookup on each value in the resulting array.

### CODE REVIEW

**Comment by piotr-cz** [comment]
Looks good. Did you test it?

**Comment by piotr-cz** [comment]
Could you please also add the `|` as an option [here](https://github.com/piotr-cz/cockpit-import/blob/v1.1.0/assets/js/filters.js#L375)?

``` JS
options = (options || {lookupKey: 'name', separator: '|'});
```

It's not possible to set options at the moment, but I'm planning to add this in future

**Comment by gryphonmyers** [comment]
Tested with recent updates and it works for my use case

**Comment by piotr-cz** [comment]
Thanks

**Pull request merged**
